# This is a workflow to run a python script every day on the latest ubuntu and python versions
name: Daily Python Script

on:
  workflow_dispatch



#on:
  #schedule:
    # Runs at 00:00 UTC every day
    #- cron: '0 0 * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      
      # Run the script
      - name: Run Script
        run: python script.py
